#[Info]
site_name: KevinHu's Website
site_url: https://devhiker.xyz
site_author: kevinHu

copyright: Copyright &copy; 2025 KevinHu
#[Config]
#[Repo Config]
repo_url: https://github.com/kevinhuky/kevinhuky.github.io 
repo_name: kevinhuky.github.io

#[扩展]
extra:
    include:
      - CNAME
    consent:
        title: Cookie consent
        description: >-
          We use cookies to recognize your repeated visits and preferences, as well
          as to measure the effectiveness of our documentation and whether users
          find what they're searching for. With your consent, you're helping us to
          make our documentation better.
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/kevinhuky

        - icon: fontawesome/solid/paper-plane
          link: mailto:kangyinghuu@gmail.com

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - admonition    
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

#[UI]
theme:
    name: 'material'                            #主题名
    favicon: assets/logo/logo.png
    language: en
    palette:
        primary: blue grey
    custom_dir: docs/templates
    icon:
        logo: material/rocket
        repo: fontawesome/brands/github         #指定仓库图标
    features:
        - search.suggest  # 启用搜索建议
        - navigation.tabs                       #在header中添加导航条
        - navigation.tabs.sticky
        - navigation.top                        #回到顶部
        - navigation.path
        - navigation.instant
        - navigation.indexes
        - navigation.prune
        - navigation.sections
        - content.blog                          # 启用博客内容特性
        - content.tabs.link                     # 启用内容标签链接
        - content.code.annotate
        - header.autohide                       # 滚动时自动隐藏/显示导航条

plugins:
  - autorefs
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - blog:
      draft: true
  - search:
#   - minify:
#       minify_html: true
#   - bibtex:
#       bib_file: "docs/references.bib"
#       csl_file: "docs/ieee.csl"
#       cite_inline: false

extra_css:
  - css/extra.css  # 加载自定义 CSS

nav:
  - About: index.md
  - Blog: 
     - blog/index.md
    

