name: Deploy Documentation

on:
  push:
    branches:
      - main  # 推送到main分支时触发
  workflow_dispatch:  # 可选：允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 推荐使用稳定版本

      - name: Install system dependencies (social cards)
        run: sudo apt-get update && sudo apt-get install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Verify CNAME
        run: |
          if [ ! -f docs/CNAME ]; then
            echo "Error: docs/CNAME file missing!" >&2
            exit 1
          fi

      - name: Build and Deploy
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动注入的token